MettSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MettSite.DataLayer;
using MettSite.ViewModels;

namespace MettSite.Controllers
{

    public class HomeController : Controller
    {
        private DataContext db = new DataContext();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            IQueryable<MettStatistics> data = from mettorder in db.MettOrders
                                              group mettorder by mettorder.Customer.Name into ordergroup
                                              select new MettStatistics()
                                              {
                                                  CustomerName = ordergroup.Key,
                                                  MettWeight = ordergroup.Sum(c => (c.MettBunNumber * c.MettShop.MettAmount)/1000),
                                                  TartarWeight = ordergroup.Sum(c => (c.TartarBunNumber * c.MettShop.TartarAmount)/1000),
                                                  BeverageCount = ordergroup.Sum(c => c.BeverageNumber)
                                              };

            return View(data.ToList());
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MettSite/Controllers/MettOrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MettSite.DataLayer;
using MettSite.Models;
using PagedList;

namespace MettSite.Controllers
{
    public class MettOrdersController : Controller
    {
        private DataContext db = new DataContext();

        // GET: MettOrders
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.DateSortParm = String.IsNullOrEmpty(sortOrder) ? "Date" : "";
            ViewBag.NameSortParm = sortOrder == "Name" ? "name_desc" : "Name";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var mettOrders = from s in db.MettOrders select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                mettOrders = mettOrders.Where(s => s.Customer.Name.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    mettOrders = mettOrders.OrderByDescending(s => s.Customer.Name);
                    break;
                case "Name":
                    mettOrders = mettOrders.OrderBy(s => s.Customer.Name);
                    break;
                case "Date":
                    mettOrders = mettOrders.OrderBy(s => s.MettOrderDate);
                    break;
                default:
                    mettOrders = mettOrders.OrderByDescending(s => s.MettOrderDate);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(mettOrders.ToPagedList(pageNumber, pageSize));
        }

        // GET: MettOrders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MettOrder mettOrder = db.MettOrders.Find(id);
            if (mettOrder == null)
            {
                return HttpNotFound();
            }
            return View(mettOrder);
        }

        // GET: MettOrders/Create
        public ActionResult Create()
        {
            ViewBag.CustomerID = new SelectList(db.Customers, "ID", "Name");
            ViewBag.MettShopID = new SelectList(db.MettShops, "ID", "ID");
            return View();
        }

        // POST: MettOrders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CustomerID,MettBunNumber,TartarBunNumber,BeverageNumber")] MettOrder mettOrder)
        {
            if (ModelState.IsValid)
            {
                var result = from s in db.MettOrders where s.MettOrderDate == DateTime.Today && s.CustomerID == mettOrder.CustomerID select s;
                int anzEntries = result.Count();
                if (anzEntries == 1)
                {
                    MettOrder foundOrder = result.First();
                    return RedirectToAction("Edit", new { id = foundOrder.ID });
                }
                else if (anzEntries > 0)
                {
                    ViewBag.CustomerID = new SelectList(db.Customers, "ID", "Name", mettOrder.CustomerID);
                    ViewBag.MettShopID = new SelectList(db.MettShops, "ID", "ID", mettOrder.MettShopID);
                    return View(mettOrder);
                }

                mettOrder.MettOrderDate = DateTime.Today;

                int latestMettShopID = db.MettShops.Max(p => p.ID);
                mettOrder.MettShopID = latestMettShopID;

                MettShop latestMettShop = db.MettShops.Find(latestMettShopID);
                double charge = (latestMettShop.MettPrice * mettOrder.MettBunNumber) + (latestMettShop.TartarPrice * mettOrder.TartarBunNumber) + (latestMettShop.BeveragePrice * mettOrder.BeverageNumber);

                mettOrder.Charge = charge;


                db.MettOrders.Add(mettOrder);

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerID = new SelectList(db.Customers, "ID", "Name", mettOrder.CustomerID);
            ViewBag.MettShopID = new SelectList(db.MettShops, "ID", "ID", mettOrder.MettShopID);
            return View(mettOrder);
        }

        // GET: MettOrders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MettOrder mettOrder = db.MettOrders.Find(id);
            if (mettOrder == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerID = new SelectList(db.Customers, "ID", "Name", mettOrder.CustomerID);
            ViewBag.MettShopID = new SelectList(db.MettShops, "ID", "ID", mettOrder.MettShopID);
            return View(mettOrder);
        }

        // POST: MettOrders/Edit/5
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int? ID)
        {
            if (ID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            MettOrder mettOrderToUpdate = db.MettOrders.Find(ID);

            if (mettOrderToUpdate.MettOrderDate == DateTime.Today)
            {
                if (TryUpdateModel(mettOrderToUpdate, "", new string[] { "MettBunNumber", "TartarBunNumber", "BeverageNumber" }))
                {
                    mettOrderToUpdate.Charge = (mettOrderToUpdate.MettShop.MettPrice * mettOrderToUpdate.MettBunNumber) + (mettOrderToUpdate.MettShop.TartarPrice * mettOrderToUpdate.TartarBunNumber) + (mettOrderToUpdate.MettShop.BeveragePrice * mettOrderToUpdate.BeverageNumber);

                    try
                    {
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    catch (DataException)
                    {
                        ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                    }
                }
            }
            return View(mettOrderToUpdate);
        }

        // GET: MettOrders/Delete/5
        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Delete failed. Try again, and if the problem persists, see your system administrator.";
            }
            MettOrder mettOrder = db.MettOrders.Find(id);
            if (mettOrder == null)
            {
                return HttpNotFound();
            }
            if (mettOrder.MettOrderDate != DateTime.Today)
            {
                return RedirectToAction("Index");
            }
            return View(mettOrder);
        }

        // POST: MettOrders/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            MettOrder currentOrder = db.MettOrders.Find(id);

            if (currentOrder.MettOrderDate != DateTime.Today)
            {
                return RedirectToAction("Index");
            }

            try
            {
                db.MettOrders.Remove(currentOrder);
                db.SaveChanges();
            }
            catch (DataException)
            {

                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MettSite/Views/Home/About.cshtml
@model IEnumerable<MettSite.ViewModels.MettStatistics>

@{
    ViewBag.Title = "Bestellstatistik";
}

<h2>Bestellstatistik</h2>

<table>
    <colgroup>
        <col width="120" />
        <col width="220" />
        <col width="220" />
        <col width="220" />
    </colgroup>
    <tr>
        <th>
            Besteller
        </th>
        <th>
            verspeistes Mett in kg
        </th>
        <th>
            verspeistes Tartar in kg
        </th>
        <th>
            Anzahl Getränke
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerName)
            </td>
            <td>
                @item.MettWeight
            </td>
            <td>
                @item.TartarWeight
            </td>
            <td>
                @item.BeverageCount
            </td>
        </tr>
    }
</table>

MettSite/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MettSite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>MettSite</h1>
    <p class="lead">MettMyDay ermöglicht dir einfaches und schnelles Bestellen deines Mettbrötchens.</p>
    <p><a href="@ViewBag.Host@Url.Action("Index", "MettOrders")" class="btn btn-primary btn-lg">Order here &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Frisches Mett</h2>
        <p>
            <img src="~/pics/mett.jpg" alt="Mett" width="300" />
        </p>
        <p><a class="btn btn-default" href="https://de.wikipedia.org/wiki/Mett" target="_blank">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Köstliches Tartar</h2>
        <p>
            <img src="~/pics/tartar.jpg" alt="Tartar" width="300" />
        </p>
        <p><a class="btn btn-default" href="https://de.wikipedia.org/wiki/Tatar" target="_blank">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Erfrischende Getränke</h2>
        <p>
            <img src="~/pics/softDrinks.jpg" alt="drinks" width="300" />
        </p>
        <p><a class="btn btn-default" href="http://www.getraenke-altinger.de" target="_blank">Learn more &raquo;</a></p>
    </div>
</div>